### ISSUE TITLE
Next release planned?

### ISSUE THREAD

**Issue by philipcunningham** [gaborv/debouncer#2]
The API after https://github.com/gaborv/debouncer/pull/1 looks really clean. @gaborv do you plan on releasing this to the Elm package index soon?

**Comment by gaborv** [comment]
@filib I cannot do that, because I had to write an effect manager to achieve the simplified API. Effect managers (just like kernel/native code) cannot be published to http://package.elm-lang.org.

If the rules change I am happy to publish it though.

Feel free to clone it and just add it to your source list -- it has no dependencies (other than `elm-lang/core`).

**Comment by philipcunningham** [comment]
Ah, of course, should have realised. Have added the dependency manually.
Feel free to close!
